version = "1"

[[extensions]]
name = "2gua.rainbow-brackets-0.0.6"
tags = [
"general"
]

[[extensions]]
name = "aaron-bond.better-comments-2.1.0"
tags = [
"general"
]

[[extensions]]
name = "adacore.ada-21.0.16"
tags = [
"ada"
]
