version = "1"

[[extensions]]
name = "2gua.rainbow-brackets"
tags = [
"general"
]

[[extensions]]
name = "aaron-bond.better-comments"
tags = [
"general"
]

[[extensions]]
name = "adacore.ada"
tags = [
"ada"
]
